spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecom_cart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=60000&tcpKeepAlive=true
    username: root
    password: root
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
