app:
  frontend-flags:
    admin-console-enabled: ${FRONTEND_FLAG_ADMIN_CONSOLE_ENABLED:true}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      connect-timeout: 2s

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
