#!/usr/bin/env python3
"""
Evaluate staged/prod release-gate drill results and emit threshold tuning deltas.

Expected input files are the release-gate artifacts generated by backend-release workflow:
- staging-release-gate.json
- production-release-gate.json
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def read_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def evaluate_env(name: str, data: dict | None) -> dict:
    if data is None:
        return {
            "environment": name,
            "present": False,
            "status": "missing",
            "smokeOutcome": "missing",
            "rollbackTriggerOutcome": "missing",
            "rollbackCallbackOutcome": "missing",
            "notes": "artifact_missing",
        }

    smoke = str(data.get("smokeOutcome", "unknown"))
    trigger = str(data.get("rollbackTriggerOutcome", "unknown"))
    callback = str(data.get("rollbackCallbackOutcome", "unknown"))

    # Drill success expectation: intentionally failed smoke should trigger rollback + callback success.
    drill_success = smoke == "failure" and trigger == "success" and callback == "success"
    # Normal healthy release expectation: no rollback needed.
    healthy_release = smoke == "success" and trigger == "skipped" and callback == "skipped"

    if drill_success:
        status = "drill_passed"
        notes = "rollback_path_validated"
    elif healthy_release:
        status = "release_passed_no_drill"
        notes = "rollback_path_not_exercised"
    else:
        status = "attention_required"
        notes = "unexpected_outcomes"

    return {
        "environment": name,
        "present": True,
        "status": status,
        "smokeOutcome": smoke,
        "rollbackTriggerOutcome": trigger,
        "rollbackCallbackOutcome": callback,
        "notes": notes,
    }


def recommend_deltas(staging: dict, production: dict) -> list[dict]:
    deltas: list[dict] = []

    any_attention = staging["status"] == "attention_required" or production["status"] == "attention_required"
    any_missing = not staging["present"] or not production["present"]
    no_drill_executed = (
        staging["status"] in {"missing", "release_passed_no_drill"}
        and production["status"] in {"missing", "release_passed_no_drill"}
    )

    if any_attention:
        deltas.append(
            {
                "setting": "ReleaseGateRollbackCallbackFailureRateCritical threshold",
                "current": ">20% over 24h (min events 3)",
                "recommended": "No relaxation; keep current and investigate callback path failures first.",
                "reason": "Drill outcome shows attention_required in at least one environment.",
            }
        )
    elif no_drill_executed:
        deltas.append(
            {
                "setting": "ReleaseGateRollbackCallbackDrillMissing window",
                "current": "14d",
                "recommended": "Keep 14d and schedule explicit staged/prod rollback drills this cycle.",
                "reason": "Rollback path not exercised in both environments.",
            }
        )
    elif any_missing:
        deltas.append(
            {
                "setting": "Drill evidence retention",
                "current": "artifact-dependent",
                "recommended": "Retain release-gate artifacts for >=30 days and attach to runbook log.",
                "reason": "Missing drill artifact for at least one environment.",
            }
        )
    else:
        deltas.append(
            {
                "setting": "ReleaseGateRollbackCallbackFailureRateCritical threshold",
                "current": ">20% over 24h (min events 3)",
                "recommended": "Optional tighten to >15% after two consecutive successful drill cycles.",
                "reason": "Both environments exercised rollback path successfully.",
            }
        )

    return deltas


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate release-gate drill outcomes.")
    parser.add_argument("--staging", default="build-artifacts/staging-release-gate.json")
    parser.add_argument("--production", default="build-artifacts/production-release-gate.json")
    parser.add_argument("--out-dir", default="build-artifacts")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    staging_raw = read_json(Path(args.staging))
    production_raw = read_json(Path(args.production))
    staging = evaluate_env("staging", staging_raw)
    production = evaluate_env("production", production_raw)
    deltas = recommend_deltas(staging, production)

    result = {
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "staging": staging,
        "production": production,
        "recommendedDeltas": deltas,
    }

    json_path = out_dir / "release-gate-drill-delta-report.json"
    md_path = out_dir / "release-gate-drill-delta-report.md"
    json_path.write_text(json.dumps(result, indent=2), encoding="utf-8")

    lines = [
        "# Release Gate Drill Delta Report",
        "",
        f"Generated at: {result['generatedAt']}",
        "",
        "| Environment | Status | Smoke | Rollback Trigger | Rollback Callback | Notes |",
        "|---|---|---|---|---|---|",
        (
            f"| staging | {staging['status']} | {staging['smokeOutcome']} | "
            f"{staging['rollbackTriggerOutcome']} | {staging['rollbackCallbackOutcome']} | {staging['notes']} |"
        ),
        (
            f"| production | {production['status']} | {production['smokeOutcome']} | "
            f"{production['rollbackTriggerOutcome']} | {production['rollbackCallbackOutcome']} | {production['notes']} |"
        ),
        "",
        "## Recommended Tuning Deltas",
    ]

    for delta in deltas:
        lines.extend(
            [
                f"- Setting: `{delta['setting']}`",
                f"  - Current: `{delta['current']}`",
                f"  - Recommended: `{delta['recommended']}`",
                f"  - Reason: `{delta['reason']}`",
            ]
        )

    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
