spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
  kafka:
    bootstrap-servers: localhost:9092

security:
  jwt:
    secret: ${JWT_SECRET:change-me-to-a-very-long-random-secret-key-for-hs256}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
