spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${PORT:8090}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  notification:
    provider: log
    max-retry: 3
    templates-resource: classpath:notification-templates.json
  cleanup:
    fixed-delay: PT6H
    dedup-retention: P14D
  kafka:
    topics:
      notification-dlq: notification.dlq.v1
      notification-alert: notification.alert.v1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
